# Generated by Django 5.1.4 on 2026-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0003_account_balance_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="id_number",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
    ]
