# Generated by Django 5.1.4 on 2026-08-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0005_registrationotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetOtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(max_length=6)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[("CHECKING", "Current"), ("SAVINGS", "Savings")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id_number",
            field=models.CharField(blank=True, default="", max_length=20, unique=True),
        ),
    ]
